<?php

return [
    [
        'slug' => 'emergency-callout',
        'title' => 'Emergency Callout',
        'short_description' => 'Flat or blowout? We reach you fast, day or night: roadside, driveway or workplace.',
        'icon' => 'fa-solid fa-truck-medical',
        'category' => 'Emergency',
        'features' => [
            '24/7 emergency mobile response',
            'Roadside, home and workplace attendance',
            'Fast typical arrival where traffic allows',
            'Safe on-site assessment and fitting',
            'Cars, vans, EVs and 4x4s covered',
        ],
        'benefits' => [
            'Help when you need it most, day or night',
            'No need to struggle to a garage',
            'Get back on the road with minimal delay',
            'Professional equipment brought to you',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Call', 'description' => 'Tell us your location and what happened.'],
            ['step' => 'Dispatch', 'description' => 'We head straight to you with the right kit.'],
            ['step' => 'Fix', 'description' => 'Repair or replace on the spot where possible.'],
            ['step' => 'Drive', 'description' => 'You\'re safely back on your journey.'],
        ],
        'faq' => [
            ['question' => 'Are you really available 24/7?', 'answer' => 'Yes. We answer day and night, including weekends and bank holidays, for emergency mobile tyre assistance.'],
            ['question' => 'How quickly can you arrive?', 'answer' => 'Typical arrival is often around 30-60 minutes depending on location, traffic and demand. We\'ll give you a clear estimate when you call.'],
        ],
    ],
    [
        'slug' => 'tyre-replacement',
        'title' => 'Tyre Replacement',
        'short_description' => 'New and part-worn tyres supplied and fitted on the spot, covering all common sizes.',
        'icon' => 'fa-solid fa-car',
        'category' => 'Fitting',
        'features' => [
            'New and part-worn tyre options',
            'Common sizes stocked or sourced quickly',
            'On-the-spot mobile fitting',
            'Quality brands including Goodyear',
            'Budget-friendly alternatives available',
        ],
        'benefits' => [
            'No tow to a garage required',
            'Choose quality or value to suit your budget',
            'Fitted correctly with proper torque',
            'Back on the road the same visit',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Size', 'description' => 'We confirm your tyre size and options.'],
            ['step' => 'Quote', 'description' => 'Clear pricing before we set off.'],
            ['step' => 'Fit', 'description' => 'Professional mobile fitting at your location.'],
            ['step' => 'Check', 'description' => 'Torque and safety checks before you leave.'],
        ],
        'faq' => [
            ['question' => 'Do you supply new and part-worn tyres?', 'answer' => 'Yes. We can supply quality new tyres (including brands such as Goodyear) as well as budget-friendly part-worn options where suitable.'],
            ['question' => 'What sizes do you cover?', 'answer' => 'We cover all common car, van and 4x4 sizes. Tell us your size when you call and we\'ll confirm availability.'],
        ],
    ],
    [
        'slug' => 'puncture-repairs',
        'title' => 'Puncture Repairs',
        'short_description' => 'Safe, professional plug and patch repairs where the tyre is suitable for repair.',
        'icon' => 'fa-solid fa-screwdriver-wrench',
        'category' => 'Repair',
        'features' => [
            'On-site puncture assessment',
            'Plug and patch where regulations allow',
            'Honest advice if replacement is safer',
            'Mobile equipment brought to you',
            'Quick turnaround to get you moving',
        ],
        'benefits' => [
            'Often cheaper than a full replacement',
            'Safe repairs carried out properly',
            'No wasted journey to a workshop',
            'Clear recommendation every time',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Inspect', 'description' => 'We check if the puncture is safely repairable.'],
            ['step' => 'Advise', 'description' => 'Honest guidance: repair or replace.'],
            ['step' => 'Repair', 'description' => 'Professional plug and patch where suitable.'],
            ['step' => 'Test', 'description' => 'Inflate, check and send you on your way.'],
        ],
        'faq' => [
            ['question' => 'Can every puncture be repaired?', 'answer' => 'Not always. Sidewall damage and some positions mean replacement is safer. We only repair when it is safe and appropriate.'],
            ['question' => 'Is a plug-only repair enough?', 'answer' => 'Where we repair, we use proper methods suited to the damage. If a tyre cannot be safely repaired, we recommend replacement.'],
        ],
    ],
    [
        'slug' => 'locking-nut-removal',
        'title' => 'Locking Nut Removal',
        'short_description' => 'Lost your locking wheel nut key? We remove stubborn locking nuts safely and professionally.',
        'icon' => 'fa-solid fa-gears',
        'category' => 'Specialist',
        'features' => [
            'Locking wheel nut removal',
            'Stubborn and seized nut extraction',
            'Damage-conscious techniques',
            'Mobile attendance at your location',
            'Ready for tyre or wheel work afterwards',
        ],
        'benefits' => [
            'No need to wait on dealer tools',
            'Get the wheel off when you need it',
            'Professional kit for tough fasteners',
            'Combined with fitting or repair if required',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Locate', 'description' => 'We come to your vehicle wherever it is.'],
            ['step' => 'Remove', 'description' => 'Specialist tools free the locking nuts.'],
            ['step' => 'Continue', 'description' => 'Fit, repair or swap as needed.'],
            ['step' => 'Finish', 'description' => 'Wheels refitted and torqued correctly.'],
        ],
        'faq' => [
            ['question' => 'Will you damage my alloy wheels?', 'answer' => 'We use professional methods designed to remove locking nuts carefully. Always tell us the wheel type when you book.'],
            ['question' => 'Can you remove nuts without the key?', 'answer' => 'Yes. That is exactly what this service is for when the key is lost or the nut is seized.'],
        ],
    ],
    [
        'slug' => 'wheel-swaps-spares',
        'title' => 'Wheel Swaps & Spares',
        'short_description' => 'Spare wheel fitting, wheel rotation and space-saver changeovers wherever you are.',
        'icon' => 'fa-solid fa-arrows-rotate',
        'category' => 'Fitting',
        'features' => [
            'Spare wheel fitting',
            'Space-saver changeovers',
            'Wheel rotation where appropriate',
            'Correct jacking and torque',
            'Advice on temporary spare limits',
        ],
        'benefits' => [
            'Safe change if you cannot do it yourself',
            'Proper tools and torque every time',
            'Help with space-savers and full-size spares',
            'Guidance on driving limits afterwards',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Call', 'description' => 'Describe your spare and location.'],
            ['step' => 'Attend', 'description' => 'We arrive with the right jacking kit.'],
            ['step' => 'Swap', 'description' => 'Safe changeover and torque checks.'],
            ['step' => 'Advise', 'description' => 'Clear guidance before you drive on.'],
        ],
        'faq' => [
            ['question' => 'Can you fit a space-saver spare?', 'answer' => 'Yes. We fit space-savers and full-size spares, and remind you of any speed or distance limits that apply.'],
            ['question' => 'Do you rotate wheels as a service?', 'answer' => 'Where appropriate we can rotate wheels as part of a mobile visit. Ask when you call.'],
        ],
    ],
    [
        'slug' => 'vans-4x4s',
        'title' => 'Vans & 4x4s',
        'short_description' => 'Cars, EVs, vans and 4x4s covered with proper jacks, torque tools and the right tyres.',
        'icon' => 'fa-solid fa-van-shuttle',
        'category' => 'Vehicles',
        'features' => [
            'Cars, EVs, vans and 4x4 coverage',
            'Heavy-duty jacks and impact tools',
            'Correct torque for each vehicle type',
            'Suitable tyre options for load ratings',
            'Mobile service at your location',
        ],
        'benefits' => [
            'One team for mixed fleets and household vehicles',
            'Equipment matched to heavier vehicles',
            'EV-aware handling and jacking points',
            'Reliable roadside and depot attendance',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Vehicle', 'description' => 'Tell us the make, model and tyre size.'],
            ['step' => 'Prepare', 'description' => 'We bring kit suited to your vehicle.'],
            ['step' => 'Service', 'description' => 'Repair, replace or swap on site.'],
            ['step' => 'Secure', 'description' => 'Torque and safety checks completed.'],
        ],
        'faq' => [
            ['question' => 'Do you work on electric vehicles?', 'answer' => 'Yes. We cover EVs along with cars, vans and 4x4s, using appropriate jacking points and equipment.'],
            ['question' => 'Can you attend commercial vans?', 'answer' => 'Yes. Vans and many light commercials are covered. Share the tyre size and location when you call.'],
        ],
    ],
    [
        'slug' => 'jumpstart',
        'title' => 'Jumpstart',
        'short_description' => 'Flat battery? We come to you with professional jumpstart kit to get your vehicle running again.',
        'icon' => 'fa-solid fa-bolt',
        'category' => 'Battery',
        'features' => [
            'Mobile battery jumpstart at your location',
            'Safe boost for cars, vans and 4x4s',
            'Roadside, home or workplace attendance',
            'Quick assessment of starting issues',
            'Advice if your battery needs replacing',
        ],
        'benefits' => [
            'Get moving again without waiting for a garage',
            'Professional kit that protects your vehicle electrics',
            'Help day or night when you are stranded',
            'Clear next steps if the battery will not hold charge',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Call', 'description' => 'Tell us your location and vehicle type.'],
            ['step' => 'Attend', 'description' => 'We arrive with jumpstart equipment.'],
            ['step' => 'Boost', 'description' => 'Safe jumpstart and system check.'],
            ['step' => 'Advise', 'description' => 'Guidance if further battery work is needed.'],
        ],
        'faq' => [
            ['question' => 'Can you jumpstart my car at home or roadside?', 'answer' => 'Yes. We provide mobile jumpstart assistance wherever you are stranded, including at home, work or the roadside.'],
            ['question' => 'What if the battery is completely dead?', 'answer' => 'We will attempt a safe jumpstart. If the battery will not hold charge, we can advise on battery recovery or replacement options.'],
        ],
    ],
    [
        'slug' => 'battery-recovery',
        'title' => 'Battery Recovery',
        'short_description' => 'Dead or failing battery recovered and replaced where needed, so you are not left stranded.',
        'icon' => 'fa-solid fa-car-battery',
        'category' => 'Battery',
        'features' => [
            'On-site battery health check',
            'Mobile battery recovery and replacement',
            'Fitting of suitable replacement batteries',
            'Safe disposal guidance for old batteries',
            'Cars, vans and 4x4s covered',
        ],
        'benefits' => [
            'Fix the root cause, not just a temporary boost',
            'No tow required for many battery jobs',
            'Clear pricing before we start',
            'Back on the road with a reliable start',
        ],
        'technologies' => [],
        'process' => [
            ['step' => 'Test', 'description' => 'We check battery condition and charging system.'],
            ['step' => 'Advise', 'description' => 'Honest recommendation: recover, replace or further checks.'],
            ['step' => 'Recover', 'description' => 'Replace or recover the battery on site where possible.'],
            ['step' => 'Confirm', 'description' => 'Start test and leave you ready to drive.'],
        ],
        'faq' => [
            ['question' => 'Do you supply and fit a new battery?', 'answer' => 'Where a replacement is needed, we can supply and fit a suitable battery at your location, subject to availability for your vehicle.'],
            ['question' => 'Is this different from a jumpstart?', 'answer' => 'Yes. A jumpstart gets you going temporarily. Battery recovery focuses on testing and resolving a flat or failing battery properly.'],
        ],
    ],
];
